### ISSUE TITLE
Artifact upload to object storage doesn't work / Artifact storage `file does not exist` error

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/data-science-pipelines-tekton#106]
/kind bug

**What steps did you take and what happened:**
When attempting to utilize a OutputPath() object, the step-copy-artifact container will throw an error stating that the artifact file does not exist and that it will skip artifact tracking.  The file does not get stored in the s3 bucket.

The following error can be generated from the following pipeline code:

```python
import os

import kfp

import kfp_tekton


def create_artifact(my_artifact: kfp.components.OutputPath()):
    import pickle

    artifact = "1, 2, 3, 4"

    print(f"artifact path: {my_artifact}")

    with open(my_artifact, "bw") as f:
        pickle.dump(artifact, f)


def consume_artifact(my_artifact: kfp.components.InputPath()):
    import pickle

    print(f"artifact path: {my_artifact}")
    
    with open(my_artifact, "br") as f:
        artifact = pickle.load(f)

    print(artifact)


create_artifact_op = kfp.components.create_component_from_func(
    create_artifact,
    base_image="image-registry.openshift-image-registry.svc:5000/openshift/python:latest",
)

consume_artifact_op = kfp.components.create_component_from_func(
    consume_artifact,
    base_image="image-registry.openshift-image-registry.svc:5000/openshift/python:latest",
)


@kfp.dsl.pipeline(
    name="Artifact Pipeline",
)
def artifact_pipeline():
    create_artifact_task = create_artifact_op()
    consume_artifact_task = consume_artifact_op(  # noqa: F841
        create_artifact_task.outputs["my_artifact"]
    )


if __name__ == "__main__":
    kfp_tekton.compiler.TektonCompiler().compile(
        artifact_pipeline, package_path=__file__.replace(".py", ".yaml")
    )
```

Which generates the following PipelineRun:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: artifact-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"create-artifact": [{"key": "artifacts/$PIPELINERUN/create-artifact/my_artifact.tgz",
      "name": "create-artifact-my_artifact", "path": "/tmp/outputs/my_artifact/data"}]}'
    tekton.dev/input_artifacts: '{"consume-artifact": [{"name": "create-artifact-my_artifact",
      "parent_task": "create-artifact"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"consume-artifact": [], "create-artifact": [["my_artifact",
      "$(workspaces.create-artifact.path)/create-artifact-my_artifact"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Artifact Pipeline"}'
spec:
  pipelineSpec:
    tasks:
    - name: create-artifact
      taskSpec:
        steps:
        - name: main
          args: [--my-artifact, $(workspaces.create-artifact.path)/create-artifact-my_artifact]
          command:
          - sh
          - -ec
          - |
            program_path=$(mktemp)
            echo -n "$0" > "$program_path"
            python3 -u "$program_path" "$@"
          - |
            def _make_parent_dirs_and_return_path(file_path: str):
                import os
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                return file_path

            def create_artifact(my_artifact):
                import pickle

                artifact = "1, 2, 3, 4"

                print(f"artifact path: {my_artifact}")

                with open(my_artifact, "bw") as f:
                    pickle.dump(artifact, f)

            import argparse
            _parser = argparse.ArgumentParser(prog='Create artifact', description='')
            _parser.add_argument("--my-artifact", dest="my_artifact", type=_make_parent_dirs_and_return_path, required=True, default=argparse.SUPPRESS)
            _parsed_args = vars(_parser.parse_args())

            _outputs = create_artifact(**_parsed_args)
          image: image-registry.openshift-image-registry.svc:5000/openshift/python:latest
        metadata:
          annotations: {pipelines.kubeflow.org/component_spec: '{"implementation":
              {"container": {"args": ["--my-artifact", {"outputPath": "my_artifact"}],
              "command": ["sh", "-ec", "program_path=$(mktemp)\necho -n \"$0\" > \"$program_path\"\npython3
              -u \"$program_path\" \"$@\"\n", "def _make_parent_dirs_and_return_path(file_path:
              str):\n    import os\n    os.makedirs(os.path.dirname(file_path), exist_ok=True)\n    return
              file_path\n\ndef create_artifact(my_artifact):\n    import pickle\n\n    artifact
              = \"1, 2, 3, 4\"\n\n    print(f\"artifact path: {my_artifact}\")\n\n    with
              open(my_artifact, \"bw\") as f:\n        pickle.dump(artifact, f)\n\nimport
              argparse\n_parser = argparse.ArgumentParser(prog=''Create artifact'',
              description='''')\n_parser.add_argument(\"--my-artifact\", dest=\"my_artifact\",
              type=_make_parent_dirs_and_return_path, required=True, default=argparse.SUPPRESS)\n_parsed_args
              = vars(_parser.parse_args())\n\n_outputs = create_artifact(**_parsed_args)\n"],
              "image": "image-registry.openshift-image-registry.svc:5000/openshift/python:latest"}},
              "name": "Create artifact", "outputs": [{"name": "my_artifact"}]}'}
        workspaces:
        - {name: create-artifact}
      timeout: 0s
      workspaces:
      - {name: create-artifact, workspace: artifact-pipeline}
    - name: consume-artifact
      taskSpec:
        steps:
        - name: main
          args: [--my-artifact, $(workspaces.consume-artifact.path)/create-artifact-my_artifact]
          command:
          - sh
          - -ec
          - |
            program_path=$(mktemp)
            echo -n "$0" > "$program_path"
            python3 -u "$program_path" "$@"
          - |
            def consume_artifact(my_artifact):
                import pickle

                print(f"artifact path: {my_artifact}")

                with open(my_artifact, "br") as f:
                    artifact = pickle.load(f)

                print(artifact)

            import argparse
            _parser = argparse.ArgumentParser(prog='Consume artifact', description='')
            _parser.add_argument("--my-artifact", dest="my_artifact", type=str, required=True, default=argparse.SUPPRESS)
            _parsed_args = vars(_parser.parse_args())

            _outputs = consume_artifact(**_parsed_args)
          image: image-registry.openshift-image-registry.svc:5000/openshift/python:latest
        metadata:
          annotations: {pipelines.kubeflow.org/component_spec: '{"implementation":
              {"container": {"args": ["--my-artifact", {"inputPath": "my_artifact"}],
              "command": ["sh", "-ec", "program_path=$(mktemp)\necho -n \"$0\" > \"$program_path\"\npython3
              -u \"$program_path\" \"$@\"\n", "def consume_artifact(my_artifact):\n    import
              pickle\n\n    print(f\"artifact path: {my_artifact}\")\n\n    with open(my_artifact,
              \"br\") as f:\n        artifact = pickle.load(f)\n\n    print(artifact)\n\nimport
              argparse\n_parser = argparse.ArgumentParser(prog=''Consume artifact'',
              description='''')\n_parser.add_argument(\"--my-artifact\", dest=\"my_artifact\",
              type=str, required=True, default=argparse.SUPPRESS)\n_parsed_args =
              vars(_parser.parse_args())\n\n_outputs = consume_artifact(**_parsed_args)\n"],
              "image": "image-registry.openshift-image-registry.svc:5000/openshift/python:latest"}},
              "inputs": [{"name": "my_artifact"}], "name": "Consume artifact"}'}
        workspaces:
        - {name: consume-artifact}
      timeout: 0s
      workspaces:
      - {name: consume-artifact, workspace: artifact-pipeline}
      runAfter: [create-artifact]
    workspaces:
    - {name: artifact-pipeline}
  timeout: 0s
  workspaces:
  - name: artifact-pipeline
    volumeClaimTemplate:
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests: {storage: 2Gi}
```

The logs output the following for the create-artifact task in tekton:

```
STEP-MAIN

artifact path: /workspace/create-artifact/create-artifact-my_artifact
STEP-COPY-ARTIFACTS

/tekton/home/tep-results/create-artifact-my_artifact file does not exist. Skip artifact tracking for my_artifact
```

**What did you expect to happen:**

When running the same code in the pre DSP Operator version of DSP the OutputPath() maps to the same workspace location as the newer version, but the `step-copy-artifacts` container looks at the correct filepath to attempt to upload it.

When running the code from above in the older version of DSP the `step-copy-artifacts` container logs the following:

```
tar: Removing leading `/' from member names
/workspace/create-artifact/create-artifact-my_artifact
Completed 177 Bytes/177 Bytes (9.9 KiB/s) with 1 file(s) remainingupload: ./my_artifact.tgz to s3://mlpipeline/artifacts/artifact-pipeline-d42da/create-artifact/my_artifact.tgz
```
And the file would be available in minio.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

It appears that both the older and newer versions of DSP write the file to the same location:

```
/workspace/create-artifact/create-artifact-my_artifact
```

In the older version of DSP it looks like DSP is using the correct location to upload the file to S3 in the copy artifact step but in the newer version it is looking for the file at the following location instead of the workspace folder:

```
/tekton/home/tep-results/create-artifact-my_artifact
```

**Environment:**

* Python Version (use `python --version`): 3.9
* SDK Version: 1.5.2
* Tekton Version (use `tkn version`): openshift-pipelines 1.9 (tekton 0.47)
* Kubernetes Version (use `kubectl version`): OCP 4.12
* OS (e.g. from `/etc/os-release`):

**Comment by gregsheremeta** [comment]
I think opendatahub-io/data-science-pipelines-operator#214 is slightly different. I'm seeing this in `step-copy-artifacts`:

```
tar: Removing leading `/' from member names
/tekton/home/tep-results/saveartifact
Completed 147 Bytes/147 Bytes (5.7 KiB/s) with 1 file(s) remainingupload: ./saveartifact.tgz to s3://greg/artifacts/test-data-passing-pipeline-1-da3fe/receive-file/saveartifact.tgz
```

So in opendatahub-io/data-science-pipelines-operator#214 case, it's trying to upload the 20MB artifact, but it ends up uploading a 0 byte tgz archive instead.

**Comment by HumairAK** [comment]
> Which generates the following PipelineRun:

@strangiato what version of the kfp-tekton are you using to compile this pipeline? I'm seeing a different result than the one you used. Your seems to be missing a `copy-results-artifacts` tekton step that is suppoed to push artifacts to s3. 

We support sdk kfp-tekton 1.5.1. Can you confirm?

If it's an older one, can you retry with 1.5.1, coupled with this workaround: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/214#issuecomment-1648014663



Edit: I see in your OP you actually mentioned you are using 1.5.2 sdk, can you try it with 1.5.1 and confirm you see the following pipelinerun after compilation: 

<details> 

<summary> pipelinerun.yaml </summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: artifact-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"create-artifact": [{"key": "artifacts/$PIPELINERUN/create-artifact/my_artifact.tgz",
      "name": "create-artifact-my_artifact", "path": "/tmp/outputs/my_artifact/data"}]}'
    tekton.dev/input_artifacts: '{"consume-artifact": [{"name": "create-artifact-my_artifact",
      "parent_task": "create-artifact"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"consume-artifact": [], "create-artifact": [["my_artifact",
      "$(workspaces.create-artifact.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/my_artifact"]]}'
    sidecar.istio.io/inject: "false"
    tekton.dev/template: ''
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Artifact Pipeline"}'
  labels:
    pipelines.kubeflow.org/pipelinename: ''
    pipelines.kubeflow.org/generation: ''
spec:
  pipelineSpec:
    tasks:
    - name: create-artifact
      taskSpec:
        steps:
        - name: main
          args:
          - --my-artifact
          - $(workspaces.create-artifact.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/my_artifact
          command:
          - sh
          - -ec
          - |
            program_path=$(mktemp)
            printf "%s" "$0" > "$program_path"
            python3 -u "$program_path" "$@"
          - |
            def _make_parent_dirs_and_return_path(file_path: str):
                import os
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                return file_path

            def create_artifact(my_artifact):
                import pickle

                artifact = "1, 2, 3, 4"

                print(f"artifact path: {my_artifact}")

                with open(my_artifact, "bw") as f:
                    pickle.dump(artifact, f)

            import argparse
            _parser = argparse.ArgumentParser(prog='Create artifact', description='')
            _parser.add_argument("--my-artifact", dest="my_artifact", type=_make_parent_dirs_and_return_path, required=True, default=argparse.SUPPRESS)
            _parsed_args = vars(_parser.parse_args())

            _outputs = create_artifact(**_parsed_args)
          image: image-registry.openshift-image-registry.svc:5000/openshift/python:latest
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        - image: busybox
          name: output-taskrun-name
          command:
          - sh
          - -ec
          - echo -n "$(context.taskRun.name)" > "$(results.taskrun-name.path)"
        - image: busybox
          name: copy-results-artifacts
          command:
          - sh
          - -ec
          - |
            set -exo pipefail
            TOTAL_SIZE=0
            copy_artifact() {
            if [ -d "$1" ]; then
              tar -czvf "$1".tar.gz "$1"
              SUFFIX=".tar.gz"
            fi
            ARTIFACT_SIZE=`wc -c "$1"${SUFFIX} | awk '{print $1}'`
            TOTAL_SIZE=$( expr $TOTAL_SIZE + $ARTIFACT_SIZE)
            touch "$2"
            if [[ $TOTAL_SIZE -lt 3072 ]]; then
              if [ -d "$1" ]; then
                tar -tzf "$1".tar.gz > "$2"
              elif ! awk "/[^[:print:]]/{f=1} END{exit !f}" "$1"; then
                cp "$1" "$2"
              fi
            fi
            }
            copy_artifact $(workspaces.create-artifact.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/my_artifact $(results.my-artifact.path)
          onError: continue
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        results:
        - name: my-artifact
          type: string
          description: /tmp/outputs/my_artifact/data
        - name: taskrun-name
          type: string
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "Create artifact",
              "outputs": [{"name": "my_artifact"}], "version": "Create artifact@sha256=17c8223da4e7b2850c87dc278f0b7d6c92048c64bea36f7d83b5571ce7dab2b9"}'
        workspaces:
        - name: create-artifact
      workspaces:
      - name: create-artifact
        workspace: artifact-pipeline
    - name: consume-artifact
      params:
      - name: create-artifact-trname
        value: $(tasks.create-artifact.results.taskrun-name)
      taskSpec:
        steps:
        - name: main
          args:
          - --my-artifact
          - $(workspaces.consume-artifact.path)/artifacts/$ORIG_PR_NAME/$(params.create-artifact-trname)/my_artifact
          command:
          - sh
          - -ec
          - |
            program_path=$(mktemp)
            printf "%s" "$0" > "$program_path"
            python3 -u "$program_path" "$@"
          - |
            def consume_artifact(my_artifact):
                import pickle

                print(f"artifact path: {my_artifact}")

                with open(my_artifact, "br") as f:
                    artifact = pickle.load(f)

                print(artifact)

            import argparse
            _parser = argparse.ArgumentParser(prog='Consume artifact', description='')
            _parser.add_argument("--my-artifact", dest="my_artifact", type=str, required=True, default=argparse.SUPPRESS)
            _parsed_args = vars(_parser.parse_args())

            _outputs = consume_artifact(**_parsed_args)
          image: image-registry.openshift-image-registry.svc:5000/openshift/python:latest
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        params:
        - name: create-artifact-trname
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "Consume artifact",
              "outputs": [], "version": "Consume artifact@sha256=63852a48dc36b1326ad1772f86f8181748f5b648cdb1387e4f54f21bfcfda53a"}'
        workspaces:
        - name: consume-artifact
      workspaces:
      - name: consume-artifact
        workspace: artifact-pipeline
      runAfter:
      - create-artifact
    workspaces:
    - name: artifact-pipeline
  workspaces:
  - name: artifact-pipeline
    volumeClaimTemplate:
      spec:
        storageClassName: kfp-csi-s3
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
```



</details>
