### ISSUE TITLE
DS Pipelines deployment with ODF fails with certificate error

### ISSUE THREAD

**Issue by mamurak** [opendatahub-io/data-science-pipelines-tekton#59]
/kind bug

**What steps did you take and what happened:**
I've installed RHODS and attempted to add DS Pipelines as a beta feature as outlined [here](https://docs.google.com/document/d/1rNYM3-hCvynfy424Wvd95v3yh1UW53lzDkoYEPeMPVY/edit?usp=sharing). I've set up ODF as the artifact store. The installer succeeds, but the `ds-pipeline` pod is crash looping with this error:
`client_manager.go:411] Failed to check if Minio bucket exists. Error: Get "[https://s3.openshift-storage.svc:443/ds-pipeline-5052f080-4b2d-4486-9e7d-32555f886319/?location=](https://s3.openshift-storage.svc/ds-pipeline-5052f080-4b2d-4486-9e7d-32555f886319/?location=)": x509: certificate signed by unknown authority`

**What did you expect to happen:**
All DS Pipelines pods should deploy successfully. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
Using OCP 4.10 through RHPDS using Let's Encrypt certificates.

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by mamurak** [comment]
Using standard (full) ODF deployment.
Set environment variables for ODF integration:
- S3_ENDPOINT=s3.openshift-storage.svc
- S3_ENDPOINT_PORT=443
- S3_ENDPOINT_SECURE=true

Bucket name and credentials as per object bucket claim.

**Comment by mamurak** [comment]
The following KfDef spec was deployed in the process:
```
spec:
  applications:
    - kustomizeConfig:
        overlays:
          - metadata-store-mariadb
          - integration-odhdashboard
          - ds-pipeline-ui
        repoRef:
          name: manifests
          path: data-science-pipelines
      name: data-science-pipelines
  repos:
    - name: manifests
      uri: 'https://github.com/red-hat-data-services/odh-manifests/tarball/master'
```
